import { jsPDF } from "jspdf";

export function sanitizeTextForPDF(str: string): string {
  if (!str) return "";

  // 1. Replace smart quotes, apostrophes, dashes, and other common non-standard symbols
  let clean = str
    .replace(/[\u2018\u2019\u02BC\u02B9]/g, "'") // smart single quotes / apostrophes
    .replace(/[\u201C\u201D\u2033]/g, '"')      // smart double quotes
    .replace(/[\u2013\u2014]/g, "-")            // dashes
    .replace(/\u2022/g, "")                    // bullet points (handled separately)
    .replace(/[•▪✓✔❖📁➔➢➤➔✓]/g, "");           // custom list decorators

  // 2. Erase multi-byte emoji surrogate pairs and other unicode dingbats and blocks
  clean = clean.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, ""); // Surrogate pairs (most emojis)
  clean = clean.replace(/[\u2600-\u27BF]/g, "");               // Dingbats & misc symbols
  clean = clean.replace(/[\u2300-\u23FF]/g, "");               // Technical symbols
  clean = clean.replace(/[\u2B50\u2B06\u2190-\u21FF]/g, "");   // Stars, Arrows
  clean = clean.replace(/[\uE000-\uF8FF]/g, "");               // Private Use Area

  // 3. Keep standard printable WinAnsi/ASCII characters (codes 32 to 126) for bulletproof rendering in jsPDF
  let asciiOnly = "";
  for (let i = 0; i < clean.length; i++) {
    const code = clean.charCodeAt(i);
    if ((code >= 32 && code <= 126) || code === 10 || code === 13) {
      asciiOnly += clean[i];
    }
  }

  // 4. Remove any remaining raw bullet markers at the start of ASCII content to avoid duplicates
  return asciiOnly.replace(/^[\s\-*+•✓✔]+/, "").trim();
}

export function exportNotesToPDF(title: string, content: string, sourceName: string) {
  const cleanTitle = sanitizeTextForPDF(title) || "Tutor Study Notes";
  const cleanSource = sanitizeTextForPDF(sourceName) || "Academic Lesson";

  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4"
  });

  // Color theme: Charcoal & Indigo (similar style to academic app)
  const primaryColor = [15, 20, 34]; // Dark Indigo (#0f1422)
  const accentColor = [79, 70, 229]; // Indigo (#4f46e5)
  const textColor = [51, 65, 85]; // Slate-700 (#334155)
  const lightGrey = [241, 245, 249]; // Light bluey grey (#f1f5f9)

  doc.setFont("Helvetica", "normal");

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - (margin * 2);

  let currentY = 20;

  // Function to draw header on each page
  const drawPageHeader = (pageNum: number) => {
    // Top banner block
    doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
    doc.rect(0, 0, pageWidth, 28, "F");

    // Top banner text
    doc.setTextColor(255, 255, 255);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.text("ACADEMIC AI TUTOR PLUS", margin, 12);

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(199, 210, 254);
    const croppedSource = cleanSource.length > 45 ? `${cleanSource.substring(0, 42)}...` : cleanSource;
    doc.text(`Study Notes • Source: ${croppedSource}`, margin, 18);

    // Date
    const today = new Date().toLocaleDateString("en-US", { year: 'numeric', month: 'long', day: 'numeric' });
    doc.setTextColor(199, 210, 254);
    doc.setFontSize(8.5);
    doc.text(today, pageWidth - margin - 35, 12);

    // Page Number
    doc.text(`Page ${pageNum}`, pageWidth - margin - 15, 18);

    // Decorative bottom border line for header
    doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
    doc.setLineWidth(1.2);
    doc.line(0, 28, pageWidth, 28);
  };

  // Function to draw footer on each page
  const drawPageFooter = (pageNum: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by Academic AI Tutor Plus with Spring Boot Integration", margin, pageHeight - 10);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 12, pageHeight - 10);
  };

  // Setup first page
  drawPageHeader(1);
  currentY = 40;

  // Title of the Notes
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  
  const titleLines = doc.splitTextToSize(cleanTitle, contentWidth);
  titleLines.forEach((line: string) => {
    doc.text(line, margin, currentY);
    currentY += 7;
  });
  
  // Colored bottom separator
  doc.setDrawColor(accentColor[0], accentColor[1], accentColor[2]);
  doc.setLineWidth(0.6);
  doc.line(margin, currentY, pageWidth - margin, currentY);
  currentY += 9;

  // Process and wrap the markdown notes content into lines
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(textColor[0], textColor[1], textColor[2]);

  const rawLines = content.split("\n");
  let currentPage = 1;

  rawLines.forEach((rawLine) => {
    let text = rawLine.trim();
    if (!text) {
      currentY += 3.5; // empty line spacing
      return;
    }

    let isHeading1 = false;
    let isHeading2 = false;
    let isHeading3 = false;
    let isBullet = false;
    let isQuote = false;

    if (text.startsWith("# ")) {
      isHeading1 = true;
      text = text.slice(2);
    } else if (text.startsWith("## ")) {
      isHeading2 = true;
      text = text.slice(3);
    } else if (text.startsWith("### ")) {
      isHeading3 = true;
      text = text.slice(4);
    } else if (text.startsWith("- ") || text.startsWith("* ")) {
      isBullet = true;
      text = text.slice(2);
    } else if (text.startsWith("> ")) {
      isQuote = true;
      text = text.slice(2);
    }

    // Wrap bold formatting delimiters to look cleaner
    text = text.replace(/\*\*/g, ""); 
    text = text.replace(/\*/g, "");
    text = text.replace(/`/g, "");

    // Clean remaining emojis, non-ASCII characters and double-indicators
    text = sanitizeTextForPDF(text);
    if (!text) {
      return; // Skip empty sanitized lines
    }

    if (isHeading1) {
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
      currentY += 3;
    } else if (isHeading2) {
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(10.5);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      currentY += 2;
    } else if (isHeading3) {
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(9.5);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      currentY += 1.5;
    } else if (isQuote) {
      doc.setFont("Helvetica", "italic");
      doc.setFontSize(9.5);
      doc.setTextColor(100, 116, 139);
    } else {
      doc.setFont("Helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(textColor[0], textColor[1], textColor[2]);
    }

    const wrapWidth = isBullet ? contentWidth - 6 : isQuote ? contentWidth - 8 : contentWidth;
    const splitLines = doc.splitTextToSize(text, wrapWidth);

    splitLines.forEach((line: string) => {
      // Check page height limit to create a new page
      if (currentY + 12 > pageHeight - 18) {
        drawPageFooter(currentPage);
        doc.addPage();
        currentPage += 1;
        drawPageHeader(currentPage);
        currentY = 38;

        // Restore appropriate fonts
        if (isHeading1) {
          doc.setFont("Helvetica", "bold");
          doc.setFontSize(12);
          doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
        } else if (isHeading2) {
          doc.setFont("Helvetica", "bold");
          doc.setFontSize(10.5);
          doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
        } else if (isHeading3) {
          doc.setFont("Helvetica", "bold");
          doc.setFontSize(9.5);
          doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
        } else if (isQuote) {
          doc.setFont("Helvetica", "italic");
          doc.setFontSize(9.5);
          doc.setTextColor(100, 116, 139);
        } else {
          doc.setFont("Helvetica", "normal");
          doc.setFontSize(9.5);
          doc.setTextColor(textColor[0], textColor[1], textColor[2]);
        }
      }

      if (isBullet) {
        doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
        // Draw elegant small bullet dot
        doc.circle(margin + 2.5, currentY - 1.2, 0.6, "F");
        doc.text(line, margin + 6, currentY);
      } else if (isQuote) {
        // Draw clear vertical bar styling
        doc.setFillColor(lightGrey[0], lightGrey[1], lightGrey[2]);
        doc.rect(margin, currentY - 3, contentWidth, 5.5, "F");
        doc.setFillColor(accentColor[0], accentColor[1], accentColor[2]);
        doc.rect(margin, currentY - 3, 1, 5.5, "F");
        doc.text(line, margin + 4, currentY);
      } else {
        doc.text(line, margin, currentY);
      }

      currentY += 5; // step line height
    });

    currentY += 1.2;
  });

  drawPageFooter(currentPage);

  const cleanName = cleanTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").slice(0, 30);
  doc.save(`study-notes-${cleanName || "export"}.pdf`);
}
